# fly.toml app configuration file generated for danestves-dev on 2023-06-02T19:17:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "danestves-dev"
primary_region = "mia"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[env]
  FLY = "true"
  HUSKY_SKIP_INSTALL = "1"
  NODE_ENV = "production"
  PORT = "8080"
  PRIMARY_REGION = "mia"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"
