name: 🌟 Refresh Content
on:
  push:
    branches:
      - main

jobs:
  refresh-cache:
    name: 🌟 Refresh Content
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "50"

      - name: 🛠 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 💿 Refresh Staging Content
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: node ./others/refresh-content.js
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME_STAGING }}

      - name: 💿 Refresh Production Content
        if: ${{ github.ref == 'refs/heads/main' }}
        run: node ./others/refresh-content.js
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
